# Generated by Django 6.0.5 on 2026-05-26 12:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('lecs_done', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('AQs_done', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('PAs_done', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('GAs_done', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
    ]
