# Generated by Django 6.0.5 on 2026-05-26 12:51

import terms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('yr', models.CharField(default=terms.models.current_yr, max_length=2)),
                ('code', models.CharField(choices=[('F1', 'first_term'), ('F2', 'second_term'), ('F3', 'third_term')], max_length=2)),
            ],
            options={
                'unique_together': {('yr', 'code')},
            },
        ),
    ]
