# Generated by Django 6.0.5 on 2026-05-26 12:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('DBMS', 'Database Management Systems'), ('PDSA', 'Programming, Data Structures and Algorithms using Python'), ('MAD-1', 'Modern Application Development I'), ('JAVA', 'Programming Concepts using Java'), ('MAD-2', 'Modern Application Development II'), ('SC', 'System Commands'), ('MLF', 'Machine Learning Foundations'), ('BDM', 'Business Data Management'), ('MLT', 'Machine Learning Techniques'), ('MLP', 'Machine Learning Practice'), ('TDS', 'Tools in Data Science'), ('BA', 'Business Analytics'), ('DLGA', 'Introduction to Deep Learning and Generative AI')], max_length=5)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terms.term')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('MAD-1P', 'Modern Application Development I - Project'), ('MAD-2P', 'Modern Application Development II - Project'), ('MLPP', 'Machine Learning Practice - Project'), ('BDMP', 'Business Data Management - Project'), ('DLGAP', 'Deep Learning and Generative AI - Project')], max_length=6)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terms.term')),
            ],
        ),
        migrations.CreateModel(
            name='SyllabusItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('lectures', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('AQs', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('PAs', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('GAs', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
    ]
