# Generated by Django 6.0.5 on 2026-06-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tag',
            field=models.CharField(choices=[('Diploma', 'Diploma'), ('Diploma in Data Science', 'Diploma in Data Science'), ('Diploma in Programming', 'Diploma in Programming')], default='Diploma', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='tag',
            field=models.CharField(choices=[('Diploma', 'Diploma'), ('Diploma in Data Science', 'Diploma in Data Science'), ('Diploma in Programming', 'Diploma in Programming')], default='Diploma', max_length=50),
            preserve_default=False,
        ),
    ]
